<?php

namespace fbt\Runtime;

class Gender
{
    public const GENDER_CONST = [
        'NOT_A_PERSON' => 0,
        'FEMALE_SINGULAR' => 1,
        'MALE_SINGULAR' => 2,
        'FEMALE_SINGULAR_GUESS' => 3,
        'MALE_SINGULAR_GUESS' => 4,
        'MIXED_SINGULAR' => 5,
        'MIXED_PLURAL' => 5,
        'NEUTER_SINGULAR' => 6,
        'UNKNOWN_SINGULAR' => 7,
        'FEMALE_PLURAL' => 8,
        'MALE_PLURAL' => 9,
        'NEUTER_PLURAL' => 10,
        'UNKNOWN_PLURAL' => 11,
    ];

    public const DATA = [
        self::GENDER_CONST['NOT_A_PERSON'] => [
            "is_male" => false,
            "is_female" => false,
            "is_neuter" => false,
            "is_plural" => false,
            "is_mixed" => false,
            "is_guess" => false,
            "is_unknown" => true,
            "subject" => 'they',
            "possessive" => 'their',
            "reflexive" => 'themself',
            "object" => 'this',
            "string" => 'unknown',
        ],
        self::GENDER_CONST['UNKNOWN_SINGULAR'] => [
            "is_male" => false,
            "is_female" => false,
            "is_neuter" => false,
            "is_plural" => false,
            "is_mixed" => false,
            "is_guess" => false,
            "is_unknown" => true,
            "subject" => 'they',
            "possessive" => 'their',
            "reflexive" => 'themself',
            "object" => 'them',
            "string" => 'unknown singular',
        ],
        self::GENDER_CONST['FEMALE_SINGULAR'] => [
            "is_male" => false,
            "is_female" => true,
            "is_neuter" => false,
            "is_plural" => false,
            "is_mixed" => false,
            "is_guess" => false,
            "is_unknown" => false,
            "subject" => 'she',
            "possessive" => 'her',
            "reflexive" => 'herself',
            "object" => 'her',
            "string" => 'female singular',
        ],
        self::GENDER_CONST['FEMALE_SINGULAR_GUESS'] => [
            "is_male" => false,
            "is_female" => true,
            "is_neuter" => false,
            "is_plural" => false,
            "is_mixed" => false,
            "is_guess" => true,
            "is_unknown" => false,
            "subject" => 'she',
            "possessive" => 'her',
            "reflexive" => 'herself',
            "object" => 'her',
            "string" => 'female singular',
        ],
        self::GENDER_CONST['MALE_SINGULAR'] => [
            "is_male" => true,
            "is_female" => false,
            "is_neuter" => false,
            "is_plural" => false,
            "is_mixed" => false,
            "is_guess" => false,
            "is_unknown" => false,
            "subject" => 'he',
            "possessive" => 'his',
            "reflexive" => 'himself',
            "object" => 'him',
            "string" => 'male singular',
        ],
        self::GENDER_CONST['MALE_SINGULAR_GUESS'] => [
            "is_male" => true,
            "is_female" => false,
            "is_neuter" => false,
            "is_plural" => false,
            "is_mixed" => false,
            "is_guess" => true,
            "is_unknown" => false,
            "subject" => 'he',
            "possessive" => 'his',
            "reflexive" => 'himself',
            "object" => 'him',
            "string" => 'male singular',
        ],
        self::GENDER_CONST['NEUTER_SINGULAR'] => [
            "is_male" => false,
            "is_female" => false,
            "is_neuter" => true,
            "is_plural" => false,
            "is_mixed" => false,
            "is_guess" => false,
            "is_unknown" => false,
            "subject" => 'they',
            "possessive" => 'their',
            "reflexive" => 'themself',
            "object" => 'them',
            "string" => 'neuter singular',
        ],
        self::GENDER_CONST['MIXED_PLURAL'] => [
            "is_male" => false,
            "is_female" => false,
            "is_neuter" => false,
            "is_plural" => true,
            "is_mixed" => true,
            "is_guess" => false,
            "is_unknown" => false,
            "subject" => 'they',
            "possessive" => 'their',
            "reflexive" => 'themselves',
            "object" => 'them',
            "string" => 'mixed plural',
        ],
        self::GENDER_CONST['FEMALE_PLURAL'] => [
            "is_male" => false,
            "is_female" => true,
            "is_neuter" => false,
            "is_plural" => true,
            "is_mixed" => false,
            "is_guess" => false,
            "is_unknown" => false,
            "subject" => 'they',
            "possessive" => 'their',
            "reflexive" => 'themselves',
            "object" => 'them',
            "string" => 'female plural',
        ],
        self::GENDER_CONST['MALE_PLURAL'] => [
            "is_male" => true,
            "is_female" => false,
            "is_neuter" => false,
            "is_plural" => true,
            "is_mixed" => false,
            "is_guess" => false,
            "is_unknown" => false,
            "subject" => 'they',
            "possessive" => 'their',
            "reflexive" => 'themselves',
            "object" => 'them',
            "string" => 'male plural',
        ],
        self::GENDER_CONST['NEUTER_PLURAL'] => [
            "is_male" => false,
            "is_female" => false,
            "is_neuter" => true,
            "is_plural" => true,
            "is_mixed" => false,
            "is_guess" => false,
            "is_unknown" => false,
            "subject" => 'they',
            "possessive" => 'their',
            "reflexive" => 'themselves',
            "object" => 'them',
            "string" => 'neuter plural',
        ],
        self::GENDER_CONST['UNKNOWN_PLURAL'] => [
            "is_male" => false,
            "is_female" => false,
            "is_neuter" => false,
            "is_plural" => true,
            "is_mixed" => false,
            "is_guess" => false,
            "is_unknown" => true,
            "subject" => 'they',
            "possessive" => 'their',
            "reflexive" => 'themselves',
            "object" => 'them',
            "string" => 'unknown plural',
        ],
    ];

    public static function getData(string $gender, string $usage)
    {
        $data = self::DATA;

        return $data[$gender]
            ? $data[$gender][$usage]
            : $data[self::GENDER_CONST['NOT_A_PERSON']][$usage];
    }
}
