<?php

namespace fbt\Transform\FbtTransform;

use dobron\DomForge\Node;

/**
 * An fbt function call, i.e. the equivalent of a BabelNodeCallExpression:
 *
 * - `fbt(contents, description, options)` (the name is null) and `fbt::c(text)`
 * - fbt constructs, e.g. `fbt::param('name', $value)` or `<fbt:param>` converted to its
 *   functional form (see GetNamespacedArgs)
 * - fbt runtime calls, e.g. `fbt::_param('name', $value)`, generated by
 *   FbtUtils::createFbtRuntimeArgCallExpression()
 *
 * Runtime values of the arguments are represented by FbtExpression.
 *
 * js~php diff: fbt constructs are often concatenated with strings, e.g.
 * `fbt('Hello ' . fbt::param('name', $name), 'desc')`, which Babel sees as a
 * BinaryExpression. In PHP, the concatenation converts the call to a string, so the
 * call is converted to a marker that is converted back to the call by the fbt() callsite
 * (see FbtCallExpression::split()).
 */
final class FbtCallExpression
{
    private const MARKER_START = "\u{E000}";
    private const MARKER_END = "\u{E001}";
    private const MARKER_PATTERN = '/\x{E000}(#?)(\d+)\x{E001}/u';

    /**
     * Calls converted to strings, which are not a part of an fbt() callsite yet
     * @var array<int, FbtCallExpression>
     */
    private static $pending = [];
    /** @var int */
    private static $nextId = 0;

    /** @var string */
    public $moduleName;
    /** @var string|null */
    public $name;
    /** @var array */
    public $arguments;
    /**
     * The DOM node of the fbt construct (if any), for error messages
     * @var Node|null
     */
    public $node;

    public function __construct(string $moduleName, ?string $name, array $arguments, ?Node $node = null)
    {
        $this->moduleName = $moduleName;
        $this->name = $name;
        $this->arguments = $arguments;
        $this->node = $node;
    }

    public function __toString(): string
    {
        $id = self::$nextId++;
        self::$pending[$id] = $this;

        return self::MARKER_START . '#' . $id . self::MARKER_END;
    }

    /**
     * Returns a marker of the call at the given index of a callsite
     */
    public static function marker(int $index): string
    {
        return self::MARKER_START . $index . self::MARKER_END;
    }

    public static function containsMarker(string $text): bool
    {
        return strpos($text, self::MARKER_START) !== false;
    }

    /**
     * Splits a string into texts and the calls that were concatenated with it.
     *
     * @param string $text
     * @param FbtCallExpression[] $calls - calls of the callsite (see FbtCallExpression::marker())
     *
     * @return array<int, string|FbtCallExpression>
     */
    public static function split(string $text, array $calls = []): array
    {
        if (! self::containsMarker($text)) {
            return [$text];
        }

        $parts = preg_split(self::MARKER_PATTERN, $text, -1, PREG_SPLIT_DELIM_CAPTURE);
        $ret = [];
        for ($i = 0, $count = count($parts); $i < $count; $i += 3) {
            if ($parts[$i] !== '') {
                $ret[] = $parts[$i];
            }

            if ($i + 2 < $count) {
                $id = (int)$parts[$i + 2];
                if ($parts[$i + 1] === '#') {
                    $ret[] = self::$pending[$id];
                    unset(self::$pending[$id]);
                } else {
                    $ret[] = $calls[$id];
                }
            }
        }

        return $ret;
    }

    /**
     * Calls the visitor for each descendant of the given node, with the list of its
     * ancestors (the closest one last), i.e. the equivalent of babel's `path.traverse()`.
     *
     * Descendants are the arguments of calls, the items of arrays, and the children of
     * DOM elements.
     *
     * @param mixed $node
     * @param callable(mixed, array): void $visitor
     * @param array $parentPath
     */
    public static function traverse($node, callable $visitor, array $parentPath = []): void
    {
        if ($node instanceof self) {
            $children = $node->arguments;
        } elseif ($node instanceof Node) {
            $children = $node->nodes;
        } elseif (is_array($node)) {
            $children = $node;
        } else {
            return;
        }

        $parentPath[] = $node;
        foreach ($children as $child) {
            $visitor($child, $parentPath);
            self::traverse($child, $visitor, $parentPath);
        }
    }

    /**
     * Returns the shape of the call, i.e. its representation without the runtime values
     * (used as a key of compiled callsites).
     *
     * @param mixed $value
     * @return mixed
     */
    public static function shape($value)
    {
        if ($value instanceof self) {
            return [
                '$call' => $value->moduleName . '::' . $value->name,
                'arguments' => self::shape($value->arguments),
            ];
        }

        if ($value instanceof FbtExpression) {
            return ['$expression' => $value->index];
        }

        if ($value instanceof Node) {
            return ['$node' => $value->outerHtml()];
        }

        if (is_array($value)) {
            return array_map([self::class, 'shape'], $value);
        }

        return $value;
    }
}
