<?php

namespace fbt\Lib;

use fbt\Transform\FbtTransform\Translate\CLDR\IntlNumberConsistency;
use fbt\Transform\FbtTransform\Translate\FBLocaleToLang;

class IntlNumberType
{
    public const LOCALE_TO_NUMBER_TYPE = [
        "pt_PT" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
    ];

    public const LANG_TO_NUMBER_TYPE = [
        "bm" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "bo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "dz" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "id" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "ig" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "ii" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "in" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "ja" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "jbo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "jv" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "jw" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "kde" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "kea" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "km" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "ko" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "lkt" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "lo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "ms" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "my" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "nqo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "root" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "sah" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "ses" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "sg" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "th" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "to" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "vi" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "wo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "yo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "yue" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "zh" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class,
        "am" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType02::class,
        "as" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType02::class,
        "bn" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType02::class,
        "fa" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType02::class,
        "gu" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType02::class,
        "hi" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType02::class,
        "kn" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType02::class,
        "mr" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType02::class,
        "zu" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType02::class,
        "ff" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType03::class,
        "fr" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType03::class,
        "hy" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType03::class,
        "kab" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType03::class,
        "pt" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType04::class,
        "ast" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "ca" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "de" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "en" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "et" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "fi" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "fy" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "gl" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "ia" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "io" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "it" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "ji" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "nl" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "sc" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "scn" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "sv" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "sw" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "ur" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "yi" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType05::class,
        "si" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType06::class,
        "ak" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType07::class,
        "bh" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType07::class,
        "guw" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType07::class,
        "ln" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType07::class,
        "mg" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType07::class,
        "nso" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType07::class,
        "pa" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType07::class,
        "ti" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType07::class,
        "wa" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType07::class,
        "tzm" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType08::class,
        "af" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "asa" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "az" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "bem" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "bez" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "bg" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "brx" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ce" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "cgg" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "chr" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ckb" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "dv" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ee" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "el" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "eo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "es" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "eu" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "fo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "fur" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "gsw" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ha" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "haw" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "hu" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "jgo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "jmc" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ka" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "kaj" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "kcg" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "kk" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "kkj" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "kl" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ks" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ksb" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ku" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ky" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "lb" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "lg" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "mas" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "mgo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ml" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "mn" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "nah" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "nb" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "nd" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ne" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "nn" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "nnh" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "no" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "nr" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ny" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "nyn" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "om" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "or" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "os" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "pap" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ps" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "rm" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "rof" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "rwk" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "saq" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "sd" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "sdh" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "seh" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "sn" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "so" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "sq" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ss" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ssy" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "st" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "syr" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ta" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "te" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "teo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "tig" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "tk" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "tn" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "tr" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ts" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ug" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "uz" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "ve" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "vo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "vun" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "wae" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "xh" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "xog" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType09::class,
        "da" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType10::class,
        "is" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType11::class,
        "mk" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType12::class,
        "fil" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType13::class,
        "tl" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType13::class,
        "lv" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType14::class,
        "prg" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType14::class,
        "lag" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType15::class,
        "ksh" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType16::class,
        "iu" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType17::class,
        "kw" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType17::class,
        "naq" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType17::class,
        "se" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType17::class,
        "sma" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType17::class,
        "smi" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType17::class,
        "smj" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType17::class,
        "smn" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType17::class,
        "sms" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType17::class,
        "shi" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType18::class,
        "mo" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType19::class,
        "ro" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType19::class,
        "bs" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType20::class,
        "hr" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType20::class,
        "sh" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType20::class,
        "sr" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType20::class,
        "gd" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType21::class,
        "sl" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType22::class,
        "dsb" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType23::class,
        "hsb" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType23::class,
        "he" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType24::class,
        "iw" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType24::class,
        "cs" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType25::class,
        "sk" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType25::class,
        "pl" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType26::class,
        "be" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType27::class,
        "lt" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType28::class,
        "mt" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType29::class,
        "ru" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType30::class,
        "uk" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType30::class,
        "br" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType31::class,
        "ga" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType32::class,
        "gv" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType33::class,
        "ar" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType34::class,
        "ars" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType34::class,
        "cy" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType35::class,
        "ceb" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType36::class,
        "fuv" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType36::class,
        "su" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType36::class,
        "gn" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType37::class,
        "fb" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType37::class,
        "la" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType37::class,
        "li" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType37::class,
        "tlh" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType37::class,
        "grc" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType37::class,
        "rw" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType37::class,
        "zza" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType37::class,
        "co" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType37::class,
        "ht" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType37::class,
        "quc" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType37::class,
        "mi" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType38::class,
        "tg" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType38::class,
        "tt" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType39::class,
        "sa" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType40::class,
        "qu" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType41::class,
        "ay" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType42::class,
        "szl" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType43::class,
        "bho" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType44::class,
        "ik" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType45::class,
        "rup" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType46::class,
        "tob" => \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType47::class,
    ];

    public static function getNumberModuleForLang(string $lang = null): IntlNumberConsistency
    {
        $cldr = self::LANG_TO_NUMBER_TYPE[$lang] ?? \fbt\Transform\FbtTransform\Translate\CLDR\IntlCLDRNumberType01::class;

        return new $cldr();
    }

    public static function getNumberModuleForLocale(string $locale = null): IntlNumberConsistency
    {
        if (array_key_exists($locale, self::LOCALE_TO_NUMBER_TYPE)) {
            $cldr = self::LOCALE_TO_NUMBER_TYPE[$locale];

            return new $cldr();
        }

        return self::getNumberModuleForLang(FBLocaleToLang::get($locale));
    }

    public static function getLanguage(string $language = null): IntlNumberConsistency
    {
        return self::getNumberModuleForLang($language);
    }

    public static function getLocale(string $locale = null): IntlNumberConsistency
    {
        return self::getNumberModuleForLocale($locale);
    }

    public static function get(string $locale = null): IntlNumberConsistency
    {
        return self::getLocale($locale);
    }
}
